[[headers]]
    for  ="/*"
    [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' unsafe-hashes 'nonce-Y2hhbmdlQ29va2llQ29uc2VudA==' 'sha256-ooI1jaWim65tBUX+C8r4Y+zdYOgwXbK3vFsTLJxbETo=' 'sha256-Dq21QDu6PN4KXgEDN+wuOsPN6tGaLoJtxqY7QWz4TqQ=' https://www.google.com/ https://www.googletagmanager.com/ https://www.google-analytics.com/; style-src 'self' *.cloudfront.net 'sha256-ESwzs/pwk6xVxIZH3YCxHKVRV9YGR02+QzCza+PCibs='; media-src 'self' *.cloudfront.net https://www.google-analytics.com/ data:;img-src 'self' *.cloudfront.net https://www.google-analytics.com/ data:"

    Feature-Policy = "vibrate 'none'; usermedia *; geolocation 'none'; midi 'none'; notifications 'none'; push 'none'; sync-xhr 'none'; microphone 'none'; camera 'none'; magnetometer 'none'; gyroscope 'none'; speaker 'none'; fullscreen 'none'; payment 'none'"

    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-Xss-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer"